stages:
  - build
  - deploy

variables:
  ECR_REPOSITORY: "website-repo"
  IMAGE_TAG: "latest"

before_script:
  - export AWS_DEFAULT_REGION=us-east-1

build:
  stage: build
  script:
    - docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
    - docker tag $ECR_REPOSITORY:$IMAGE_TAG 154260813552.dkr.ecr.us-east-1.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
    - $(aws ecr get-login --no-include-email --region us-east-1)
    - docker push 154260813552.dkr.ecr.us-east-1.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

deploy:
  stage: deploy
  script:
    - echo "Deploying to AWS..."
    - aws eks --region $AWS_REGION update-kubeconfig --name $EKS_CLUSTER_NAME
  only:
    - main
