version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm test

  deploy:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Deploy to AWS
          command: |
            # Example deployment commands
            echo "Deploying to AWS..."
            # Your deployment commands here, such as updating Kubernetes manifests or running Helm commands

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          context: aws
